server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:assets
    username: sa
    password:

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
